server:
   port: 8761
spring:
   security:
      user:
         name: myapp
         password: MyApp
eureka:
   instance:
      hostname: localhost
   server:
      enableSelfPreservation: false
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---
server:
   port: 8761
spring:
   profiles: server1
eureka:
   instance:
      hostname: server1
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://server2/eureka/
---
server:
   port: 8762
spring:
   profiles: server2
eureka:
   instance:
      hostname: server2
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
         defaultZone: http://server1/eureka/