server:
   port: 0
spring:
   application:
      name: MyDiscoveryClient
eureka:
   instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      preferIpAddress: false
      lease-renewal-interval-in-seconds: 60
   client:
      serviceUrl:
         defaultZone: http://myapp:MyApp@localhost:8761/eureka